name: io_mindtechapps_hw
description: "Mindtech Apps HW"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  # Standard Flutter dependencies
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Routing
  go_router: ^15.1.2

  # State management & dependency injection
  get_it: ^8.0.3
  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0
  provider: ^6.1.5

  # Networking
  dio: ^5.8.0+1

  # Device info
  device_info_plus: ^11.4.0
  package_info_plus: ^8.3.0

  # Firebase
  firebase_core: ^3.13.1
  firebase_analytics: ^11.4.6
  firebase_crashlytics: ^4.3.6
  firebase_remote_config: ^5.4.4

  # Data handling
  cached_network_image: ^3.4.1
  file_picker: ^10.1.9
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^10.0.0-beta.4
  share_plus: ^11.0.0

  # Other data related
  collection: ^1.19.1
  cross_file: ^0.3.4+2
  equatable: ^2.0.7
  flutter_hooks: ^0.21.2
  json_annotation: ^4.9.0
  rxdart: ^0.28.0

  # Utils
  envied: ^1.1.1
  flutter_screenutil: ^5.9.3
  image: ^4.5.4
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  upgrader: ^11.4.0
  path: ^1.9.1

  # UI/UX components
  flutter_svg: ^2.1.0
  flutter_native_splash: ^2.4.6
  auto_size_text: ^3.0.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  envied_generator: ^1.1.1
  flutter_gen_runner: ^5.10.0
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  custom_lint: ^0.7.5
  io_mindtechapps_hw_custom_lint:
    path: ./linter/

flutter_gen:
  output: lib/core/resources/gen/
  line_length: 120
  integrations:
    flutter_svg: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/generation/app_icon.png"
  image_path_android: "assets/generation/app_icon_android.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/generation/splash.png

  android_12:
    image: assets/generation/splash.png
    icon_background_color: "#ffffff"

  web: false

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: "Jost"
      fonts:
        - asset: "assets/fonts/Jost-Thin.ttf"
          weight: 100
        - asset: "assets/fonts/Jost-ThinItalic.ttf"
          weight: 100
          style: italic
        - asset: "assets/fonts/Jost-ExtraLight.ttf"
          weight: 200
        - asset: "assets/fonts/Jost-ExtraLightItalic.ttf"
          weight: 200
          style: italic
        - asset: "assets/fonts/Jost-Light.ttf"
          weight: 300
        - asset: "assets/fonts/Jost-LightItalic.ttf"
          weight: 300
          style: italic
        - asset: "assets/fonts/Jost-Regular.ttf"
          weight: 400
        - asset: "assets/fonts/Jost-Italic.ttf"
          weight: 400
          style: italic
        - asset: "assets/fonts/Jost-Medium.ttf"
          weight: 500
        - asset: "assets/fonts/Jost-MediumItalic.ttf"
          weight: 500
          style: italic
        - asset: "assets/fonts/Jost-SemiBold.ttf"
          weight: 600
        - asset: "assets/fonts/Jost-SemiBoldItalic.ttf"
          weight: 600
          style: italic
        - asset: "assets/fonts/Jost-Bold.ttf"
          weight: 700
        - asset: "assets/fonts/Jost-BoldItalic.ttf"
          weight: 700
          style: italic
        - asset: "assets/fonts/Jost-ExtraBold.ttf"
          weight: 800
        - asset: "assets/fonts/Jost-ExtraBoldItalic.ttf"
          weight: 800
          style: italic
        - asset: "assets/fonts/Jost-Black.ttf"
          weight: 900
        - asset: "assets/fonts/Jost-BlackItalic.ttf"
          weight: 900
          style: italic
