name: Run PR validation

on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "17.0"
      NO_APPROVAL_NEEDED: 'false'
    steps:
      - name: Check PR Title
        id: check
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          if [[ "$PR_TITLE" == *"[NO APPROVAL]"* ]]; then
            echo "NO_APPROVAL_NEEDED=true" >> $GITHUB_ENV
          else
            echo "NO_APPROVAL_NEEDED=false" >> $GITHUB_ENV
          fi

      - name: Check out repository
        if: env.NO_APPROVAL_NEEDED == 'false'
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Check for Changelog
        if: env.NO_APPROVAL_NEEDED == 'false' && github.event.pull_request.base.ref == 'develop' && github.event.pull_request.head.ref != 'develop'
        run: |
          change=$(git diff-tree --no-commit-id --name-status -r origin/develop..HEAD | grep -P '(A|M)\t.+'| grep CHANGELOG.md |awk '{print $2}')
          if [ -z "$change" ]
          then
            echo "You must update the CHANGELOG.md"
            exit 1
          fi

      - uses: actions/setup-java@v1
        if: env.NO_APPROVAL_NEEDED == 'false'
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Flutter FVM config action
        if: env.NO_APPROVAL_NEEDED == 'false'
        uses: kuhnroyal/flutter-fvm-config-action/setup@v3
        with:
          cache: true

      - run: flutter clean
        if: env.NO_APPROVAL_NEEDED == 'false'

      # Get flutter dependencies.
      - run: flutter pub get
        if: env.NO_APPROVAL_NEEDED == 'false'
      - run: flutter pub get
        if: env.NO_APPROVAL_NEEDED == 'false'
        working-directory: linter

      # Check for any formatting issues in the code.
      - run: dart format --line-length 120 --set-exit-if-changed .
        if: env.NO_APPROVAL_NEEDED == 'false'

      # Statically analyze the Dart code for any errors.
      - run: dart analyze .
        if: env.NO_APPROVAL_NEEDED == 'false'
      - run: dart run custom_lint
        if: env.NO_APPROVAL_NEEDED == 'false'

      # Run tests for our flutter project.
      #- run: flutter test --coverage
      #  if: env.NO_APPROVAL_NEEDED == 'false'
      #- name: Setup .NET Core # Required to execute ReportGenerator
      #  if: env.NO_APPROVAL_NEEDED == 'false'
      #  uses: actions/setup-dotnet@v3
      #  with:
      #    dotnet-version: 6.x
      #    dotnet-quality: "ga"

      #- name: ReportGenerator
      #  if: env.NO_APPROVAL_NEEDED == 'false'
      #  uses: danielpalme/ReportGenerator-GitHub-Action@5.1.17
      #  with:
      #    reports: coverage/lcov.info
      #    targetdir: coverage
      #    reporttypes: Cobertura
      #    title: "Code coverage"
      #- name: Code Coverage Report
      #  if: env.NO_APPROVAL_NEEDED == 'false'
      #  uses: irongut/CodeCoverageSummary@v1.3.0
      #  with:
      #    filename: coverage/Cobertura.xml
      #    badge: true
      #    fail_below_min: false
      #    format: markdown
      #    hide_branch_rate: true
      #    hide_complexity: true
      #    indicators: true
      #    output: both
      #    thresholds: "50 75"
      #- name: Add Coverage PR Comment
      #  if: env.NO_APPROVAL_NEEDED == 'false' && github.event_name == 'pull_request'
      #  uses: marocchino/sticky-pull-request-comment@v2
      #  with:
      #    recreate: true
      #    path: code-coverage-results.md
